import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from 'next/link';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-6">
              <div className="flex items-center">
                <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
                  CBA Consult IT Management Framework
                </h1>
                <span className="ml-3 px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full">
                  v3.2.0
                </span>
              </div>
              <nav className="flex space-x-4">
                <Link href="/dashboard" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Dashboard
                </Link>
                <Link href="/employee-app-store" className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 font-medium">
                  App Store
                </Link>
                <Link href="/application-procurement" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Procurement
                </Link>
                <Link href="/policies" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Policies
                </Link>
                <Link href="/blueprints" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Blueprints
                </Link>
                <Link href="/compliance" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Compliance
                </Link>
                <Link href="/compliance-dashboard" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Compliance Dashboard
                </Link>
                <Link href="/defender-activities" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Defender Activities
                </Link>
                <Link href="/feedback" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Feedback
                </Link>
                <Link href="/escalations" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                  Escalations
                </Link>
                <Link href="/docs" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white font-semibold">
                  Docs
                </Link>
              </nav>
            </div>
          </div>
        </header>
        <main>{children}</main>
        <footer className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 mt-12">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
            <div className="flex justify-between items-center">
              <p className="text-sm text-gray-500 dark:text-gray-400">
                © 2025 CBA Consult IT Management Framework. All rights reserved.
              </p>
              <div className="flex space-x-4">
                <a href="#" className="text-sm text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                  Documentation
                </a>
                <a href="#" className="text-sm text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                  Support
                </a>
                <a href="#" className="text-sm text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">
                  GitHub
                </a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
