# Module manifest for module 'ICT-Governance-Framework'
# Generated by: GitHub Copilot & Gemini
# Generated on: 2025-08-22

@{
    RootModule = 'ICT-Governance-Framework.psm1'
    ModuleVersion = '1.0.0'
    Author = 'GitHub Copilot & Gemini'
    CompanyName = 'Unknown'
    Copyright = '(c) 2025 GitHub Copilot. All rights reserved.'
    Description = 'A PowerShell module to help manage and automate governance controls for Azure resources.'
    FunctionsToExport = @(
        'Initialize-GovFramework',
        'Connect-GovAzure',
        'Get-GovPolicyComplianceSummary',
        'Get-GovNonCompliantResources',
        'New-GovDashboardReport',
        'New-GovAssessmentReport',
        'Write-GovLog'
    )
    RequiredModules = @(
        @{ModuleName = 'Az.Accounts'; ModuleVersion = '2.12.3'},
        @{ModuleName = 'Az.Resources'; ModuleVersion = '6.7.0'},
        @{ModuleName = 'Az.PolicyInsights'; ModuleVersion = '1.6.2'}
    )
    PrivateData = @{
        CONFIG = @{
            LogPath             = 'governance-logs'
            ReportPath          = 'governance-reports'
            TemplatesPath       = 'governance-templates'
            PolicyDefinitionsPath = 'policy-definitions'
        }
    }
}
